<a href="https://colab.research.google.com/github/SathKay/AI-ML/blob/main/Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# step 1: import the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [5]:
# step 2: reading the data and splitting it to input and output
dataset = pd.read_csv('/content/sales.csv')
inputx = dataset.iloc[:, 0:3].values
outputy = dataset.iloc[:, 3].values
print(outputy)

[22.1 10.4  9.3 18.5 12.9  7.2 11.8 13.2 15.6 12.2]


In [6]:
print(dataset)

   TVBudget  RadioBudget  NewspaerBudget  Sales
0     230.1         37.8            69.2   22.1
1      44.5         39.3            45.1   10.4
2      17.2         45.9            69.3    9.3
3     151.5         41.3            58.5   18.5
4     180.8         10.8            58.4   12.9
5       8.7         48.9            75.0    7.2
6      57.5         32.8            23.5   11.8
7     120.2         19.6            11.6   13.2
8     144.1         16.0            40.3   15.6
9     111.6         12.6            37.9   12.2


In [7]:
# step 3: select one fourth of the data for testing and two thirds for training
input_train, input_test, output_train, output_test = train_test_split(inputx, outputy, test_size = 1/4, random_state = 0)


In [8]:
# step 4: selecting the simple Linear Regression model
model = LinearRegression()
print("\nThe parameters of the model are\n\n",model.get_params())
#print(model.set_params())
print("\nThe model we are using is ", model.fit(input_train, output_train))


The parameters of the model are

 {'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

The model we are using is  LinearRegression()


In [13]:
# step 5: testing or model prediction using testinput
tvbudget = float(input("\nGive the TV Budget value  "))
radiobudget = float(input("\nGive the Radio Budget value  "))
newspaperbudget = float(input("\nGive the Newspaper Budget value  "))
testinput = [[tvbudget,radiobudget,newspaperbudget]]
predicted_output = model.predict(testinput)
print('\nThe test input is as follows ',testinput)
print('\nThe predicted sales unit is ',predicted_output)
yes = input("\nCan I proceed\n")



Give the TV Budget value  230.1

Give the Radio Budget value  37.8

Give the Newspaper Budget value  69.2

The test input is as follows  [[230.1, 37.8, 69.2]]

The predicted sales unit is  [22.46769379]

Can I proceed
yes


In [19]:
# step 6: Printing the testing results
print("\nThe test input (Tv Budget, Radio Budget and Newspaper Budget) is as follows \n")
print(input_test)
predicted_output = model.predict(input_test)
print("\nThe predicted sales units for the test input is as follows \n")
print(predicted_output)


The test input (Tv Budget, Radio Budget and Newspaper Budget) is as follows 

[[ 17.2  45.9  69.3]
 [144.1  16.   40.3]
 [180.8  10.8  58.4]]

The predicted sales units for the test input is as follows 

[ 8.27822465 14.43134582 15.68524304]
